# Deployment for Frontend Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  labels:
    app: karsajobs
spec:
  replicas: 1 # replicas number
  selector:
    matchLabels:
      # pods for deployment
      app: karsajobs
      tier: frontend
  template:
    metadata:
      labels:
	# the pods
        app: karsajobs
        tier: frontend
    spec:
      containers:
      - name: frontend-server
	# pull image from github package
        image: ghcr.io/azcat01/karsajobs-ui:latest
        ports:
          - containerPort: 8000 # expose this port so that the website is accessible
