version: 2.1 # version of circleci

jobs:
  # hadolint to check Dockerfile best practice
  lint-dockerfile:
    docker:
      - image: cimg/base:current # base image (ubuntu)
    steps:
      - checkout # check and pull from git repository
      - setup_remote_docker # to run docker from remote machine
      - run: 
          command: | 
            docker pull hadolint/hadolint # get hadolint
            docker run --rm -i hadolint/hadolint < Dockerfile # run hadolint with Dockerfile as input
  test-app: # testing app
    docker:
      - image: cimg/go:1.15 # use golang docker image
    steps:
      - checkout
      - run:
          command: go test -v -short --count=1 $(go list ./...) # test app
  # build app
  build-app-karsajobs:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: ./build_push_image_karsajobs.sh # push image using script
workflows:
  karsajobs-image:
    # concurrently do the jobs
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
