# PV and PVC for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # set storage to 2 gibs
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo" # mount data to path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
